// src/utils/iconosServicios.js
import {
    FaWifi,
    FaParking,
    FaDog,
    FaMotorcycle,
    FaUtensils,
    FaWheelchair,
    FaLaptop,
    FaLeaf,
    FaCreditCard,
    FaSmokingBan,
    FaChild,
    FaUserShield,
    FaShoppingBag,
    FaLock,
    FaCalendarCheck,
    FaHome,
    FaStore,
    FaMapMarkedAlt,
    FaPhoneAlt,
    FaClock,
    FaStar,
    FaGlassCheers,
    FaBroom,
    FaCamera,
    FaCar,
    FaShower,
    FaCouch,
    FaFan,
    FaSnowflake,
    FaBatteryFull,
    FaTrashAlt,
    FaBolt,
    FaTruck,
    FaUtensilSpoon,
    FaHandshake,
    FaChair,
    FaPeopleArrows,
    FaShieldAlt,
    FaTshirt,
    FaToilet,
    FaQuestionCircle,
  } from "react-icons/fa";
  
  export const iconosServicios = {
    // Servicios generales
    "wifi gratis": <FaWifi className="text-blue-500" />,
    "wifi": <FaWifi className="text-blue-500" />,
    "wi-fi": <FaWifi className="text-blue-500" />, 
    "Wi-fi": <FaWifi className="text-blue-500" />,
    "estacionamiento": <FaParking className="text-gray-700" />,
    "pet friendly": <FaDog className="text-green-600" />,
    "delivery": <FaMotorcycle className="text-orange-600" />,
    "comida en el lugar": <FaUtensils className="text-red-600" />,
    "acceso silla ruedas": <FaWheelchair className="text-purple-600" />,
    "trabajo remoto": <FaLaptop className="text-teal-500" />,
    "opciones veganas": <FaLeaf className="text-green-500" />,
    "acepta tarjetas": <FaCreditCard className="text-indigo-500" />,
    "prohibido fumar": <FaSmokingBan className="text-gray-500" />,
    "área para niños": <FaChild className="text-yellow-600" />,
    "seguridad": <FaUserShield className="text-sky-600" />,
    "tienda online": <FaShoppingBag className="text-pink-500" />,
    "ambiente seguro": <FaLock className="text-red-400" />,
    "reserva previa": <FaCalendarCheck className="text-emerald-600" />,
    "atención domicilio": <FaHome className="text-fuchsia-500" />,
    "local físico": <FaStore className="text-gray-700" />,
    "cómo llegar": <FaMapMarkedAlt className="text-indigo-600" />,
    "teléfono disponible": <FaPhoneAlt className="text-green-600" />,
  
    // Servicios de atención
    "horarios extendidos": <FaClock className="text-orange-500" />,
    "alta calificación": <FaStar className="text-yellow-500" />,
    "ambiente social": <FaGlassCheers className="text-pink-500" />,
    "limpieza": <FaBroom className="text-lime-600" />,
    "fotografía profesional": <FaCamera className="text-violet-600" />,
    "estacionamiento gratuito": <FaCar className="text-blue-700" />,
  
    // Servicios tipo alojamiento o consultorios
    "ducha disponible": <FaShower className="text-cyan-500" />,
    "sala de espera": <FaCouch className="text-gray-500" />,
    "ventilador": <FaFan className="text-blue-300" />,
    "aire acondicionado": <FaSnowflake className="text-blue-500" />,
    "carga batería": <FaBatteryFull className="text-green-500" />,
    "recolección de basura": <FaTrashAlt className="text-gray-400" />,
    "energía eléctrica": <FaBolt className="text-yellow-400" />,
  
    // Otros servicios comunes
    "envío": <FaTruck className="text-teal-600" />,
    "menú disponible": <FaUtensilSpoon className="text-orange-600" />,
    "asistencia personalizada": <FaHandshake className="text-rose-500" />,
    "asientos disponibles": <FaChair className="text-indigo-400" />,
    "distanciamiento social": <FaPeopleArrows className="text-red-500" />,
    "protección personal": <FaShieldAlt className="text-slate-600" />,
    "pruebas de ropa": <FaTshirt className="text-amber-600" />,
    "baños disponibles": <FaToilet className="text-gray-600" />,
  };
  
  export const iconoGenerico = <FaQuestionCircle className="text-gray-400" />;
  