import {
    FaUtensils,
    FaShoppingCart,
    FaHotel,
    FaHospital,
    FaPaintBrush,
    FaCar,
    FaWrench,
    FaGraduationCap,
    FaDumbbell,
    FaCocktail,
    FaMusic,
    FaTshirt,
    FaLeaf,
    FaHammer,
    FaBook,
    FaTv,
    FaLaptop,
    FaDog,
    FaHome,
    FaPlug,
    FaQuestionCircle,
    FaAppleAlt,
  } from "react-icons/fa";
  
  export const iconosCategorias = {
    "electrónica": <FaTv />,
    "restaurantes": <FaUtensils className="text-red-500" />,
    "compras": <FaShoppingCart className="text-purple-500" />,
    "hoteles": <FaHotel className="text-yellow-500" />,
    "salud": <FaHospital className="text-pink-500" />,
    "arte y entretenimiento": <FaPaintBrush className="text-indigo-500" />,
    "automotriz": <FaCar className="text-gray-700" />,
    "servicios": <FaWrench className="text-blue-500" />,
    "educación": <FaGraduationCap className="text-green-600" />,
    "gimnasios y fitness": <FaDumbbell className="text-orange-600" />,
    "bares y vida nocturna": <FaCocktail className="text-fuchsia-500" />,
    "música y eventos": <FaMusic className="text-yellow-600" />,
    "moda y ropa": <FaTshirt className="text-pink-600" />, 
    "ropa": <FaTshirt className="text-pink-600" />,
    "productos naturales": <FaLeaf className="text-green-500" />,
    "construcción": <FaHammer className="text-gray-600" />,
    "librerías": <FaBook className="text-indigo-600" />,
    "tecnología": <FaLaptop className="text-blue-700" />,
    "Electrónica": <FaPlug className="text-yellow-400" />,
    "mascotas": <FaDog className="text-brown-500" />,
    "inmobiliaria": <FaHome className="text-cyan-500" />,
    "electricistas": <FaPlug className="text-yellow-400" />, 
    "alimentos": <FaAppleAlt />,

  };
  
  export const iconoCategoriaGenerico = <FaQuestionCircle className="text-gray-400" />;
  